var app_lang = {
    enter: 'შესვლა',
    login: 'მეტსახელი',
    password: 'პაროლი',
    password_retry: 'გაიმეორეთ პაროლი',
    registration: 'რეგისტრაცია',
    back: 'უკან',
    next: 'შემდეგი',
    please_wait: 'ჩატვირთვა...',
    register: 'რეგისტრაცია',
    register_name: 'სახელი (მაქს. 15 სიმბოლო A-Z)',
    register_login: 'მეტსახელი (მაქს. 15 სიმბოლო A-Z 0-9)',
    register_password: 'პაროლი (მაქს. 15 სიმბოლო A-Z)',
    sex: 'სქესი',
    women: 'მდედრობითი',
    men: 'მამრობითი',
    select: 'აირჩიეთ',
    birthdate: 'დაბადების თარიღი ',
    city: 'ქალაქი',
    info: 'დამატებითი ინფორმაცია',
    error: 'შეცდომა',
    success: 'OK',
    close: 'დახურვა',
    connection_error: 'ოპერაციის შესრულება შეუძლებელია. გთხოვთ, შეამოწმოთ ინტერნეტ კავშირი',
    inet_connection_error: 'ინტერნეტთან კავშირი ვერ მოხერხდა',
    ok: 'დახურვა',
    newses: 'სიახლეები',
    messages: 'გზავნილები',
    congratulations: 'განცხადებები',
    online: 'საიტზეა',
    author: 'ავტორი',
    unknown: 'უცნობი',
    age: 'ასაკი',
    girlsandboys: 'ყველა',
    boys: 'ბიჭები',
    girls: 'გოგონები',
    /* gallery */

    gallery: 'გალერეა',
    capturePhoto: 'გადაღება',
    uploadPhoto: 'ატვირთვა',
    uploadSuccesfully: 'სურათი წარმატებით დაემატა',
    /* talks */
    send: 'გაგზავნა',
    text: 'ტექსტი',
    /* user card */

    user: 'მომხმარებელი',
    rating: 'რეიტინგი',
    albom: 'ალბომი',
    nick: 'მეტსახელი',
    searchwho: 'მიზანი',
    gifts: 'საჩუქრები',
    friends: 'მეგობრები',
    regtime: 'რეგისტრაციის დრო',
    lastvisit: 'ბოლო ვიზიტი',
    talks_list: 'დიალოგები',
    n_messages: 'ახალი',
    /* Remote Keys */

    DEFAULT_SYSTEM_ERROR: 'ოპერაციის შესრულებისას დაფიქსირდა შეცდომა',
    INVALID_USERNAME: 'მეტსახელი არასწორადაა შეყვანილი',
    LOGIN_ALREADY_EXISTS: 'მეტსახელი დაკავებულია. გთხოვთ, შეარჩიოთ სხვა',
    INVALID_USERNAME_LENGHT: 'მეტსახელი უნდა იყოს მინიმუმ 3 და მაქსიმუმ 15 სიმბოლო',
    INVALID_PASSWORD: 'პაროლი არასწორადაა შეყვანილი',
    INVALID_PASSWORD_LENGHT: 'პაროლის სიგრძე უნდა იყოს მინიმუმ 6 / მაქსიმუმ 15 სიმბოლო',
    PASSWORD_RETRY_ERROR: 'პაროლები არ ემთხვევა',
    INVALID_NAME: 'სახელი არასწორადაა შეყვანილი',
    INVALID_SEX: 'გთხოვთ, აირჩიოთ სქესი',
    INVALID_DAY: 'გთხოვთ, აირჩიოთ დაბადების დღე',
    INVALID_MONTH: 'გთხოვთ, აირჩიოთ დაბადების თვე',
    INVALID_YEAR: 'გთხოვთ, აირჩიოთ დაბადების წელი',
    INVALID_INFO: 'გთხოვთ, მიუთითოთ ინფორმაცია თქვენს შესახებ',
    LOGIN_OR_PASSWORD_INCORRECT: 'მეტსახელი ან პაროლი არასწორია',
    USER_NOT_FOUND: 'მომხმარებელი არ მოიძებნა',
    NO_USER_WRITE_ACCESS: 'თქვენ არ გაქვთ მიწერის უფლება',
    ONLY_FIENDS_ACCEPTED: 'მიწერა შესაძლებელია მხოლოდ მეგობრებისთვის',
    SEND_FRIEND_REQUEST: 'გამოგიგზავნათ მეგობრობის თხოვნა',
    ACCEPT_FRIEND_REQUEST: 'დაეთანხმა მეგობრობის თხოვნას',
    LIKE_YOUR_PHOTO: 'მოსწონს თქვენი ფოტო',
    ADD_COMMENT_ON_YOUR_PHOTO: 'დატოვა კომენტარი თქვენს ფოტოზე',
    FRIEND_ADDED: 'მომხმარებელი დაემატა თქვენი მეგობრების სიაში',
    USER_IS_IN_FRIENDS: 'მომხმარებელი უკვე არის თქვენი მეგობრების სიაში',
    USER_DELETED_FROM_IGNOR: 'მომხმარებელი ამოშლილია ბლოკირებულთა სიიდან',
    USER_ADDED_IN_IGNOR: 'მომხმარებელი დაემატა ბლოკირებულთა სიაში',
    /* Raylway */

    location: 'მისამართი',
    phone: 'ტელ. ნომერი',
    email: 'ელ. ფოსტა',
    agreeadvbyphone: 'რეკლამა ტელეფონზე',
    agreeadvbyemail: 'რეკლამა ელ.ფოსტაზე',
    firstname: 'სახელი',
    lastname: 'გვარი',
    raylway: 'რკინიგზა',
    departure: 'გამგზავრება',
    arrival: 'ჩასვლა',
    date: 'თარიღი',
    find: 'ძებნა',
    ccy: 'GEL',
    weekDays: [
        'Sunday',
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday'
    ],
    months: ["იანვარი", "თებერვალი", "მარტი",
        "აპრილი", "მაისი", "ივნისი", "ივლისი", "აგვისტო", "სექტემბერი",
        "ოქტომბერი", "ნოემბერი", "დეკემბერი"],
    count: 'რაოდენობა',
    please_select_count: 'გთხოვთ, აირჩიოთ რაოდენობა',
    standard_place: 'ჩვეულებრივი',
    child_place: 'საბავშვო',
    find_places: 'ადგილების ძებნა',
    wagon: 'ვაგონი',
    seat_number: 'ადგილი: #',
    price: 'ფასი ',
    passenger_info: 'მგზავრის მონაცემები',
    checkout: 'შეძენა',
    GEL: ' GEL',
    pin: 'პირადი ნომერი',
    save: 'შენახვა',
    passenger_info_error: 'აუცილებელია ყველა მგზავრის მონაცემების სრულად შეყვანა'

};

